### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by pettrs** [McAJBen/animation-skipper#3]
![image](https://github.com/McAJBen/animation-skipper/assets/75093127/452a4fe4-6b08-43f6-9088-ac4e932a2af7)

later, not layer :)

also, honestly preferred the white text instead of transparent. possibly make the text selective color, so you can reduce opacity yourself if you prefer transparent.

when you click away from an action when canceling. it seems ver long before the black screen fades away. the fade timer does not seem to effect the delay from when you cancel the action. possibly reduce to instant?

**Comment by McAJBen** [comment]
Fixed in version 1.2.

---

> when you click away from an action when canceling. it seems ver long before the black screen fades away

This can be changed with the `Debounce duration`. A higher debounce duration helps to prevent issues like [this](https://github.com/McAJBen/animation-skipper/issues/2), but does cause a delay while the plugin waits for the animation to repeat.
